name: Deploy to Netlify

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploying to Netlify
    steps:
    - uses: actions/checkout@master

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.300

    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: Publish Blazor webassembly using dotnet
      run: dotnet publish MyBlazorPwaDemo.csproj -c Release -o release --nologo
